# Generated by Django 4.1 on 2022-12-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairros',
            fields=[
                ('id_bairro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_bairro', models.CharField(max_length=126)),
            ],
            options={
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=126)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Est_Fisico',
            fields=[
                ('id_est_fisico', models.AutoField(primary_key=True, serialize=False)),
                ('est_fisico', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Estados Físicos',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nome_genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tarefa', models.CharField(max_length=100)),
                ('situacao_tarefa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=126)),
                ('dta_nasc_usuario', models.DateField()),
                ('telefone_usuario', models.CharField(max_length=15)),
                ('email_usuario', models.EmailField(max_length=70)),
                ('numero_usuario', models.CharField(max_length=10)),
                ('logradouro_usuario', models.CharField(max_length=126)),
                ('id_bairro_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.bairros')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_livro', models.CharField(max_length=100)),
                ('editora_livro', models.CharField(max_length=45)),
                ('autor_livro', models.CharField(max_length=100)),
                ('dta_publicacao_livro', models.DateField()),
                ('qtd_paginas_livro', models.IntegerField()),
                ('id_est_fisico_livro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.est_fisico')),
                ('id_genero_livro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.generos')),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=126)),
                ('dta_nasc_funcionario', models.DateField()),
                ('telefone_funcionario', models.CharField(max_length=15)),
                ('email_funcionario', models.CharField(max_length=70)),
                ('numero_funcionario', models.CharField(max_length=10)),
                ('logradouro_funcionario', models.CharField(max_length=126)),
                ('id_bairro_funcionario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.bairros')),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id_emprestimos', models.AutoField(primary_key=True, serialize=False)),
                ('dta_emprestimo', models.DateField()),
                ('dta_devolucao', models.DateField()),
                ('id_funcionario_emprestimos', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.funcionarios')),
                ('id_livro_emprestimos', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livros')),
                ('id_usuario_emprestimos', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.AddField(
            model_name='bairros',
            name='id_cidade_bairro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidades'),
        ),
    ]
